- name: creating container config
  hosts: rhel9
  gather_facts: false
  tasks:
   - name: creating container
     containers.podman.podman_container:
       name: Maintenance_page
       image: registry.redhat.io/rhel8/httpd-24
       state: started
       volumes:
        - "/home/ipexdr/container2:/var/www/html" 
       publish:
        - '8090:8080'
